dna = 'GATGCGTACTTCGTGCCTGTAGAAACCGTCTTGGGCAGATCGCGGTCCCCTTCTTACACGTATGGTCAGAAGGGCATACTACTGGGCCGGATCATTTTCGGCACCAGAAGATATGGCCTCGAAATCTGACATCATACCCGCCCAGCCAAATATGTCAAAGGTTCCTTTTTGGACCTATCTCGCAAACAATACTAGACTCGGCCGCTACTTCGTTATGCCGATCGTGCGGGTGCACCGCCAGGAAGGACACATTCCCATTGACCCTCTTCTAGTATTTGTTGTCATCCGGAAATGGGTGTTCCTTTACGGACAGTTAATGTGCGAAGACTCTTCTTTTTTACTAAAGCGTACGGCTCGGTTGGTTCATATGTTAGTCTTGCCACATATACACATAACCATGGGCTCGTGTTACCGGCTGTAATTCGCGTACTACTACATGCTTCCGTTACTGAACCGCATCGATTCGCGATGTGAATCCGGCGTTTGATGGTCTCGCCGAGTACCCTCGATTGACAAACGTTCCGGCAGTTCGCCCCTAACCACGTCTGATCTGTCTGAGCTCTGAAGCCGCATATGTGCTCTAAAAAGTACCACTCGCTCTTCGCAACCCCTCGCACCCGTCGCAAGGACTTGAAAAAACACAAAGCTCGGAAGATCTCCATGTTAAAATGTACTACATTTCCCAGTTGCCAAACGCTTCTGTTTGGGTTGGAGGACTTTTAAGGAGACGCGAACCGACCCAAGCGTGGCACGCTAACACGGTTCCCAAGGGACGTTAAGGTTTTCTCACTCATACGCGCGCCCGCCCCCATCACGCGGCACGTCCCTTCAGTTTCCACCTCAGATGATTCGGTTGAGACCGATTCGTA'

# so_luong_a = 0
# so_luong_g = 0
# so_luong_c = 0
# so_luong_t = 0

sl_a, sl_c, sl_g, sl_t = 0, 0, 0, 0

# iterate = lặp lại
for loai_nu in dna:
    if loai_nu == 'A':
        sl_a += 1 # tương đương với sl_a = sl_a + 1
    
    if loai_nu == 'C': #python phân biệt chữ hoa và chữ thường!
        sl_c += 1
    
    if loai_nu == 'G':
        sl_g += 1
    
    if loai_nu == 'T':
        sl_t += 1

print(sl_a, sl_c, sl_g, sl_t)